"""add_auto_approve_auto_continue_to_runs

Revision ID: b6ce246eb3c7
Revises: 057faecfdd86
Create Date: 2026-03-13 01:21:04.744803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ce246eb3c7'
down_revision: Union[str, None] = '057faecfdd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('auto_approve', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('runs', sa.Column('auto_continue', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'auto_continue')
    op.drop_column('runs', 'auto_approve')
    # ### end Alembic commands ###
